In [1]:
import numpy as np
from datascience import *

%matplotlib inline 
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [2]:
def triple(x):
    return 3 * x

In [3]:
triple(3)

9

In [4]:
print(triple(make_array(1, 2, 3)))

[3 6 9]


In [5]:
triple(np.arange(3, 15, 3))

array([ 9, 18, 27, 36])

In [6]:
def precent_of_total(s):
    return np.round(s/sum(s) * 100)

In [7]:
precent_of_total(np.arange(3, 15, 3))

array([ 10.,  20.,  30.,  40.])

In [8]:
def hypotenuse(x, y):
    return(x ** 2 + y ** 2) ** 0.5

In [9]:
hypotenuse(9, 12)

15.0

In [10]:
def age(year):
    age = 2026 - year
    return age

In [11]:
age(2006)

20

In [12]:
def name_and_age(name, year):
    '''
    Returns a string with name and age of person.
    Arguments:
        name: the name of the person
        year: the year the person was born
    Returns:
        string with name and age.
    '''
    return name + ' is ' + str(age(year)) + ' years old.' 

In [13]:
name_and_age('Ridge', 2006)

'Ridge is 20 years old.'

In [14]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Joe', 'Mary'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)

In [15]:
ages

Person,Birth Year
Jim,1985
Pam,1988
Joe,1967
Mary,1904


In [16]:
ages.apply(name_and_age, 'Person', 'Birth Year')

array(['Jim is 41 years old.', 'Pam is 38 years old.',
       'Joe is 59 years old.', 'Mary is 122 years old.'],
      dtype='<U22')

In [17]:
ages.apply(age, 'Birth Year')

array([ 41,  38,  59, 122])

In [18]:
name_and_age?

Signature: name_and_age(name, year)
Docstring:
Returns a string with name and age of person.
Arguments:
    name: the name of the person
    year: the year the person was born
Returns:
    string with name and age.
File:      ~\appdata\local\temp\ipykernel_19400\985281959.py
Type:      function

In [19]:
cones = Table.read_table('data/cones.csv')
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [20]:
cones.group('Flavor', np.average)

Flavor,Color average,Price average
bubblegum,,4.75
chocolate,,5.08333
strawberry,,4.4


In [21]:
cones.drop('Color').group('Flavor', np.mean)

Flavor,Price mean
bubblegum,4.75
chocolate,5.08333
strawberry,4.4


In [22]:
cones = cones.drop('Color')

In [23]:
cones.group('Flavor', list)

Flavor,Price list
bubblegum,[4.75]
chocolate,"[4.75, 5.25, 5.25]"
strawberry,"[3.5499999999999998, 5.25]"


## Cross-classify with two-group columns

In [24]:
cones = Table.read_table('data/cones.csv')
cones.group('Flavor')

Flavor,count
bubblegum,1
chocolate,3
strawberry,2


In [25]:
cones.group(['Flavor', 'Color'], np.mean)

Flavor,Color,Price mean
bubblegum,pink,4.75
chocolate,dark brown,5.25
chocolate,light brown,4.75
strawberry,pink,4.4


In [26]:
cones.with_rows(['coffee', 'brown', '7.56'])

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75
c,o,f
b,r,o
7,.,5


## Cross-classify with pivot

In [28]:
cones.pivot('Flavor', 'Color')

Color,bubblegum,chocolate,strawberry
dark brown,0,2,0
light brown,0,1,0
pink,1,0,2


In [30]:
cones.pivot('Flavor', 'Color', 'Price', collect=np.average)

Color,bubblegum,chocolate,strawberry
dark brown,0,5.25,0
light brown,0,4.75,0
pink,4.75,0,4.4


### Groups or Pivot?

In [32]:
skyscrapers = Table.read_table('data/skyscrapers.csv')

In [35]:
skyscrapers

name,material,city,height,completed
One World Trade Center,mixed/composite,New York City,541.3,2014
Willis Tower,steel,Chicago,442.14,1974
432 Park Avenue,concrete,New York City,425.5,2015
Trump International Hotel & Tower,concrete,Chicago,423.22,2009
Empire State Building,steel,New York City,381,1931
Bank of America Tower,mixed/composite,New York City,365.8,2009
Stratosphere Tower,concrete,Las Vegas,350.22,1996
Aon Center,steel,Chicago,346.26,1973
John Hancock Center,steel,Chicago,343.69,1969
Chrysler Building,steel,New York City,318.9,1930


In [40]:
np.unique(skyscrapers.column('name'), return_counts=True)

(array(['1 Bank of America Center', '1 MiMA Tower', '1 New York Plaza', ...,
        'Yacht Harbor Tower II', 'Yorkville Towers', 'theWit Hotel'],
       dtype='<U72'),
 array([1, 1, 1, ..., 1, 1, 1]))

In [43]:
sky = skyscrapers.drop('name', 'completed')

In [44]:
sky

material,city,height
mixed/composite,New York City,541.3
steel,Chicago,442.14
concrete,New York City,425.5
concrete,Chicago,423.22
steel,New York City,381
mixed/composite,New York City,365.8
concrete,Las Vegas,350.22
steel,Chicago,346.26
steel,Chicago,343.69
steel,New York City,318.9


In [46]:
sky.group('material')

np.max(sky.column('height'))

541.29998779297

In [50]:
max_height = sky.sort('height', descending=True)
max_height

material,city,height
mixed/composite,New York City,541.3
steel,Chicago,442.14
concrete,New York City,425.5
concrete,Chicago,423.22
steel,New York City,381
mixed/composite,New York City,365.8
concrete,Las Vegas,350.22
steel,Chicago,346.26
steel,Chicago,343.69
steel,New York City,318.9


In [102]:
city = sky.select('material', 'city', 'height').group(['city', 'material'], np.max)
mat = sky.select('material', 'height').group('material', np.max)
city


city,material,height max
Atlanta,concrete,264.25
Atlanta,mixed/composite,311.8
Atlanta,steel,169.47
Austin,concrete,208.15
Austin,steel,93.6
Baltimore,concrete,161.24
Baltimore,steel,155.15
Boston,concrete,121.92
Boston,mixed/composite,139
Boston,steel,240.79


In [101]:
skyscrapers.where('height', are.above(425))

name,material,city,height,completed
One World Trade Center,mixed/composite,New York City,541.3,2014
Willis Tower,steel,Chicago,442.14,1974
432 Park Avenue,concrete,New York City,425.5,2015


**Task**: For each city, find the height difference between the tallest steel building and the tallest concrete building.

In [122]:
city = sky.select('material', 'city', 'height').group(['city', 'material'], np.max)

city_steel = city.group(['city', 'material'], np.max)

In [123]:
concrete =city.where('material', 'concrete')
steel = city.where('material', 'steel')
steel

city,material,height max
Atlanta,steel,169.47
Austin,steel,93.6
Baltimore,steel,155.15
Boston,steel,240.79
Charlotte,steel,179.23
Chicago,steel,442.14
Cincinnati,steel,175
Cleveland,steel,215.8
Columbus,steel,169.3
Dallas,steel,270.06


In [124]:
joined = steel.join('city', concrete)
diff = abs(joined.column('height max') - joined.column('height max_2'))
df = joined.with_column('diff', diff)
df

city,material,height max,material_2,height max_2,diff
Atlanta,steel,169.47,concrete,264.25,94.78
Austin,steel,93.6,concrete,208.15,114.55
Baltimore,steel,155.15,concrete,161.24,6.09001
Boston,steel,240.79,concrete,121.92,118.87
Charlotte,steel,179.23,concrete,265.48,86.25
Chicago,steel,442.14,concrete,423.22,18.92
Cincinnati,steel,175,concrete,125,50
Cleveland,steel,215.8,concrete,125,90.8
Columbus,steel,169.3,concrete,79.25,90.05
Dallas,steel,270.06,concrete,176.48,93.58


## Join

In [135]:
full = Table.read_table('data/nc-est2019-agesex-res.csv')
census = full.select('SEX', 'AGE', 'POPESTIMATE2019')

In [136]:
census.group('SEX')

SEX,count
0,102
1,102
2,102


In [139]:
sex_codes = Table().with_columns(
    'SEX CODE', make_array(0, 1, 2),
    'SEX Descriptor', make_array('ALL', 'Male', 'Female')
)

full.join('SEX', sex_codes, 'SEX CODE')

SEX,AGE,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,SEX Descriptor
0,0,3944153,3944160,3951430,3963092,3926570,3931258,3954787,3983981,3954773,3893990,3815343,3783052,ALL
0,1,3978070,3978090,3957730,3966225,3977549,3942698,3948891,3973133,4002903,3972711,3908830,3829599,ALL
0,2,4096929,4096939,4090621,3970654,3978925,3991740,3958711,3966321,3991349,4020045,3987032,3922044,ALL
0,3,4119040,4119051,4111688,4101644,3981531,3991017,4005928,3974351,3982984,4006946,4033038,3998665,ALL
0,4,4063170,4063186,4077346,4121488,4111490,3992502,4004032,4020292,3989750,3997280,4018719,4043323,ALL
0,5,4056858,4056872,4064521,4087054,4131049,4121876,4004576,4017589,4035033,4003452,4008443,4028281,ALL
0,6,4066381,4066412,4072904,4074531,4096631,4141126,4133372,4017388,4031568,4048018,4014057,4017227,ALL
0,7,4030579,4030594,4042990,4082821,4084175,4106756,4152666,4145872,4030888,4044139,4058370,4022319,ALL
0,8,4046486,4046497,4025501,4052773,4092559,4094513,4118349,4165033,4158848,4042924,4054236,4066194,ALL
0,9,4148353,4148369,4125312,4035319,4062726,4103052,4106068,4130887,4177895,4170813,4053179,4061874,ALL
